# Generated by Django 5.2.16 on 2026-08-04 14:44

import timezone_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="Unique URL code for this clinic (e.g. 'oak-aug-2026'). Phase 2 auto-generates this; in the back office it can be typed.", max_length=40, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('date', models.DateField(help_text='The calendar date of the clinic.')),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('timezone', timezone_field.fields.TimeZoneField(default='America/Los_Angeles', help_text="Per-event IANA zone. open_at/close_at are entered and shown in this zone, and it sets when 'noon' (the auto-lottery deadline) is.")),
                ('open_at', models.DateTimeField(db_index=True, help_text="Sign-up window opens (stored UTC; edited in the event's tz).")),
                ('close_at', models.DateTimeField(db_index=True, help_text="Sign-up window closes (stored UTC; edited in the event's tz).")),
                ('x_seen', models.PositiveIntegerField(help_text='X — number of animals this clinic will see.')),
                ('y_waitlist', models.PositiveIntegerField(help_text='Y — number of waitlist animals (computed on the remainder after the selected bucket fills).')),
                ('z_applicants', models.PositiveIntegerField(help_text='Z — soft cap on registrations/owners. New signups are rejected once reached; a small concurrent overshoot is acceptable.')),
                ('offers_flea_deworming', models.BooleanField(default=False)),
                ('offers_microchip', models.BooleanField(default=False)),
                ('offers_vaccination', models.BooleanField(default=False)),
                ('offers_vet', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('live', 'Live (open for signups)'), ('lottery_run', 'Lottery run'), ('active', 'Active (clinic day)'), ('completed', 'Completed')], default='draft', editable=False, max_length=20)),
                ('lottery_run_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('next_staff_id', models.PositiveIntegerField(default=1000, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date', 'name'],
            },
        ),
    ]
