# Generated by Django 5.2.16 on 2026-08-04 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('live', 'Live'), ('lottery_run', 'Lottery run'), ('active', 'Active (clinic day)'), ('completed', 'Completed')], default='draft', editable=False, max_length=20),
        ),
    ]
