# Generated by Django 5.2.16 on 2026-08-04 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, help_text="Unique URL code for this clinic (e.g. 'oak-aug-2026'). Leave blank to generate it from the event name.", max_length=40, unique=True),
        ),
    ]
