# Generated by Django 5.2.16 on 2026-08-04 14:52

import django.db.models.deletion
import register.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_id', models.PositiveIntegerField(blank=True, editable=False, help_text='Assigned by the lottery (1..999) or staff (>=1000); read-only outside the allocation services.', null=True)),
                ('id_source', models.CharField(blank=True, choices=[('lottery', 'Lottery'), ('staff', 'Staff')], editable=False, help_text='Which allocator assigned animal_id (set together with it).', max_length=10, null=True)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('selected', 'Selected'), ('waitlisted', 'Waitlisted'), ('not_selected', 'Not selected'), ('checked_in', 'Checked in')], default='registered', max_length=20)),
                ('edit_token', models.CharField(db_index=True, default=register.models.generate_edit_token, max_length=64, unique=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish')], default='en', max_length=2)),
                ('printed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('checked_in_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('result_sms_state', models.CharField(blank=True, choices=[('sending', 'Sending'), ('sent', 'Sent (accepted)'), ('failed', 'Failed'), ('unknown', 'Unknown')], default=None, editable=False, max_length=10, null=True)),
                ('result_sms_sent_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('sms_opt_out', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(help_text='E.164 (Phase 3 validates + normalizes).', max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=300)),
                ('creation_source', models.CharField(choices=[('public', 'Public (owner)'), ('staff', 'Staff')], default='public', max_length=10)),
                ('admitted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admitted_by_user', models.ForeignKey(blank=True, editable=False, help_text='The staff user that admitted an existing public row (1000+ ID).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admitted_registrations', to=settings.AUTH_USER_MODEL)),
                ('created_by_user', models.ForeignKey(blank=True, help_text='The staff user that created a staff-source row (null for public).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_registrations', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event')),
            ],
            options={
                'ordering': ['event', 'last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=100)),
                ('age', models.CharField(help_text="Free text, e.g. '3 years' or '8 months'.", max_length=30)),
                ('breed', models.CharField(blank=True, default='', max_length=100)),
                ('color', models.CharField(blank=True, default='', max_length=100)),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('MN', 'Male-Neutered'), ('FS', 'Female-Spayed')], default='', max_length=2)),
                ('services_requested', models.JSONField(default=list)),
                ('last_vaccinated_date', models.DateField(blank=True, null=True)),
                ('medical_concern', models.TextField(blank=True, default='')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='register.registration')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='registration',
            constraint=models.UniqueConstraint(condition=models.Q(('animal_id__isnull', False)), fields=('event', 'animal_id'), name='unique_animal_id_per_event'),
        ),
    ]
