# Generated by Django 5.2.16 on 2026-08-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('MN', 'Male-Neutered'), ('FS', 'Female-Spayed'), ('U', 'Unknown')], default='', max_length=2),
        ),
    ]
