# Generated by Django 5.2.16 on 2026-08-04 19:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_status'),
        ('register', '0002_alter_animal_sex'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='registration',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('animal_id__isnull', True), ('id_source__isnull', True)), models.Q(('animal_id__isnull', False), ('id_source__isnull', False), models.Q(models.Q(('animal_id__gte', 1), ('animal_id__lte', 999), ('id_source', 'lottery')), models.Q(('animal_id__gte', 1000), ('id_source', 'staff')), _connector='OR')), _connector='OR'), name='animal_id_source_range_valid'),
        ),
    ]
